name: computational-publications

channels:
  - conda-forge
  - pip
  - defaults

dependencies:
  # Main Python
  - python=3.8

  - jupyter-book

  # Publication packages
  - sphinxcontrib-bibtex
  - ghp-import

  # Jupyter environment
  # - jupyterlab
  # - notebook
  # - jupyter_contrib_nbextensions
  # - nbclean
  # - autopep8
  # - nb_black
