name: computational-publications

channels:
  - conda-forge
  - defaults

dependencies:
  # Main Python
  - python=3.8

  # Publication packages
  - sphinxcontrib-bibtex
  - ghp-import

  # Jupyter environment
  - jupyterlab
  - notebook
  - jupytext
  - jupyter_contrib_nbextensions
  - nbclean
  - autopep8
  - nb_black

  # Jupyter Book
  - pip
  - pip:
    - jupyter-book
